=== Shunseii/bahar/apps/api/src/dictionary.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "created_at_timestamp": {
      "type": "integer",
      "description": "A UNIX timestamp in seconds that represents the same date as `created_at`."
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "updated_at_timestamp": {
      "type": "integer",
      "description": "A UNIX timestamp in seconds that represents the same date as `updated_at`."
    },
    "word": {
      "type": "string",
      "description": "A word or expression in Arabic."
    },
    "definition": {
      "type": "string",
      "description": "The definition of the word in Arabic."
    },
    "translation": {
      "type": "string",
      "description": "The English translation of the word."
    },
    "type": {
      "type": "string",
      "description": "The type of the word.",
      "enum": ["ism", "fi'l", "harf", "expression"]
    },
    "root": {
      "type": "array",
      "description": "An array of letters representing the root letters of the word.",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "description": "Any tags associated with the word. These can denote things like the context.",
      "items": {
        "type": "string"
      }
    },
    "antonyms": {
      "type": "array",
      "description": "Any antonyms of the word.",
      "items": {
        "type": "object",
        "properties": {
          "word": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "type": "array",
      "description": "Examples using the word.",
      "items": {
        "type": "object",
        "properties": {
          "sentence": {
            "description": "A sentence using the word.",
            "type": "string"
          },
          "context": {
            "description": "The context of the sentence. This can refer to casual or formal contexts, for example.",
            "type": "string"
          },
          "translation": {
            "description": "The English translation of the sentence.",
            "type": "string"
          }
        },
        "required": ["sentence"]
      }
    },
    "morphology": {
      "type": "object",
      "description": "The morphological properties of the word.",
      "properties": {
        "ism": {
          "type": "object",
          "description": "The morphological properties of an ism such as the gender and the different plural and singular forms.",
          "properties": {
            "singular": {
              "type": "string"
            },
            "dual": {
              "type": "string"
            },
            "plurals": {
              "type": "array",
              "description": "The (broken) plural forms of the word. Use harakat to indicate inflection.",
              "items": {
                "type": "object",
                "properties": {
                  "word": {
                    "type": "string"
                  },
                  "details": {
                    "type": "string",
                    "description": "Any additional details about this form such as frequency of usage or context."
                  }
                },
                "required": ["word"]
              }
            },
            "gender": {
              "type": "string",
              "enum": ["masculine", "feminine"]
            },
            "inflection": {
              "type": "string",
              "description": "The inflection of the word. This refers to how many case endings the word can take. Three means it can take all three, two means it can only take raf' and nasb, and one means it is indeclinable.",
              "enum": ["indeclinable", "diptote", "triptote"]
            }
          }
        },
        "verb": {
          "type": "object",
          "description": "The morphological properties of a fi'l such as the verb conjugations and noun forms.",
          "properties": {
            "huroof": {
              "type": "array",
              "description": "A list of the prepositions that can be used with the fi'l. Typically, if the meaning with the preposition is completely different, then it's better to create a separate dictionary entry.",
              "items": {
                "type": "object",
                "properties": {
                  "harf": {
                    "type": "string"
                  },
                  "meaning": {
                    "type": "string",
                    "description": "The meaning of the fi'l when used with the preposition. If it is the same as the base meaning, then leave this blank."
                  }
                },
                "required": ["harf"]
              }
            },
            "past_tense": {
              "type": "string"
            },
            "present_tense": {
              "type": "string"
            },
            "active_participle": {
              "type": "string"
            },
            "passive_participle": {
              "type": "string"
            },
            "imperative": {
              "type": "string"
            },
            "masadir": {
              "type": "array",
              "description": "A list of the possible verbal noun forms.",
              "items": {
                "type": "object",
                "properties": {
                  "word": {
                    "type": "string"
                  },
                  "details": {
                    "type": "string",
                    "description": "Any additional details about this form such as frequency of usage or context."
                  }
                },
                "required": ["word"]
              }
            },
            "form": {
              "type": "string",
              "description": "The form or pattern of the verb from I - X."
            },
            "form_arabic": {
              "type": "string",
              "description": "The form or pattern of the verb in Arabic using the root ف-ع-ل."
            }
          }
        }
      }
    },
    "flashcard": {
      "$ref": "flashcard.json"
    },
    "flashcard_reverse": {
      "$ref": "flashcard.json"
    }
  },
  "required": ["id", "word", "translation"]
}

=== Shunseii/bahar/apps/web/src/lib/db/import/v1/v1_sample_export_without_flashcards.json
[
  {
    "id": "N3WMRETxCG0v84LOv09Yq",
    "word": "مِمحاَة",
    "translation": "eraser",
    "definition": "",
    "type": "ism",
    "root": [],
    "tags": ["معهد الخليل", "قصص النبيين"],
    "antonyms": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "bbaGH3bQym70S-wxEJM7p",
    "word": "عِمارة",
    "translation": "art of building",
    "definition": "",
    "type": "ism",
    "root": ["ع", "م", "ر"],
    "tags": ["معهد الخليل", "قصص النبيين"],
    "antonyms": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "e_kin_ZSPgJGQLpPAMgsB",
    "word": "رُزّ",
    "translation": "rice",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "3U--cmjLNVMjM2VkTmB-d",
    "word": "حقيبة",
    "translation": "bag",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [
          {
            "word": "حقائب"
          }
        ],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "XAApYaKaEEHZ99YCrDRO4",
    "word": "أَسَد",
    "translation": "lion",
    "definition": "",
    "type": "ism",
    "root": [],
    "tags": [],
    "antonyms": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [
          {
            "word": "أُسُد"
          }
        ],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "55hDJ6ycFxlAvs6sIoWUm",
    "word": "اعتنى بـ",
    "translation": "to give attention to",
    "definition": "اهتمّ بـ",
    "type": "fi'l",
    "root": ["ع", "ن", "ي"],
    "examples": [],
    "morphology": {
      "verb": {
        "huroof": [],
        "past_tense": "",
        "present_tense": "",
        "active_participle": "",
        "passive_participle": "",
        "imperative": "",
        "masadir": [],
        "form": "",
        "form_arabic": ""
      }
    }
  },
  {
    "id": "vTPo_bgJodcNbQ_sHXUvB",
    "word": "سَلَطة",
    "translation": "salad",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "a7BEUVKfwdfTMaD-JGoku",
    "word": "مُدَّة",
    "translation": "interval, period of time, duration",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "mNiMleBdMxoDfT4HYoKGU",
    "word": "صِحِّيّ",
    "translation": "healthy",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "QvRsypI0qrF-npTrbH5Xq",
    "word": "استراح",
    "translation": "to relax",
    "definition": "",
    "type": "fi'l",
    "root": ["ر", "و", "ح"],
    "examples": [],
    "morphology": {
      "verb": {
        "huroof": [],
        "past_tense": "",
        "present_tense": "يستريح",
        "active_participle": "",
        "passive_participle": "",
        "imperative": "",
        "masadir": [],
        "form": "",
        "form_arabic": ""
      }
    }
  },
  {
    "id": "YX0G-BtUFAQbnakJKWXIv",
    "word": "لِحيَة",
    "translation": "beard",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [
          {
            "word": "لِحى"
          }
        ],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "EpYBtRrZlq0uRmb9kanx-",
    "word": "لذلك",
    "translation": "so...",
    "definition": "فـ",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "gbn1cLuTvJDckXrMpOCna",
    "word": "نَظّارة",
    "translation": "glasses",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "EVgDox9hU7WE1_BoIp8up",
    "word": "مُزدَحِم",
    "translation": "crowded",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "MfylAiiaS2RBRu6iSSGZ1",
    "word": "العلَم",
    "translation": "proper name",
    "definition": "اسم الإنسان",
    "type": "ism",
    "root": [],
    "tags": [],
    "antonyms": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "XH5UAfJiEBvQGfQUugVw7",
    "word": "مُجتَهِد",
    "translation": "hard-working",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "4O7KKK1TM5G4HJ7IpgdSa",
    "word": "ناقة",
    "translation": "she-camel",
    "definition": "",
    "type": "ism",
    "root": [],
    "tags": ["معهد الخليل", "قصص النبيين"],
    "antonyms": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "aBpKcviHiSBC2gVQbKyIB",
    "word": "كَسول",
    "translation": "lazy",
    "definition": "ضد نشيط",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "5go0_lPqO8f44pAfUqFAr",
    "word": "عاصِفَة",
    "translation": "storm",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [
          {
            "word": "عَواصِف"
          }
        ],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "YbQef1rrfVBnev-iWFd6D",
    "word": "نَشيط",
    "translation": "energetic",
    "definition": "ضد كسول",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "a5RLSf5ETcdICDry3rx7d",
    "word": "جَمع",
    "translation": "plural",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "d1YpGKq0EZx43AVPgvxLW",
    "word": "مثنّى",
    "translation": "dual",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "kNsgLQwRsjdfcOCdEAsln",
    "word": "مذكَّر",
    "translation": "masculine",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "R_TjbHo2TZXnsPx7wqIMr",
    "word": "مؤنّث",
    "translation": "feminine",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "NDwY8ZJrkxe5p-rnsQwIT",
    "word": "سَفينَة",
    "translation": "ship",
    "definition": "",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
        "dual": "",
        "plurals": [
          {
            "word": "سُفُن",
            "details": ""
          }
        ],
        "gender": "masculine",
        "inflection": "triptote"
      }
    }
  },
  {
    "id": "Z-xlNKvqz8wtM9PJscm0Y",
    "word": "حِوار",
    "translation": "conversation",
    "definition": "محادثة",
    "type": "ism",
    "root": [],
    "examples": [],
    "morphology": {
      "ism": {
        "singular": "",
